### ISSUE TITLE
Super large audio file problems

### ISSUE THREAD

**Issue by SenYan1999** [lumaku/ctc-segmentation#13]
Thanks for your work! 

The time length of my audio file is more than 1 hour, so there are some problems when I tried your example codes in ESPNet2 and NeMo using my own data.

In ESPNet2, either my gpu memory nor my cpu memory isn't large enough to run the code.

In NeMo, it hints my as followings.
```
INFO:root:CTC segmentation of 62154 chars to 8700.20s audio (217505 indices).
WARNING:root:IndexError: Backtracking was not successful, the window size might be too small.
WARNING:root:Increasing the window size to: 64000
WARNING:root:IndexError: Backtracking was not successful, the window size might be too small.
ERROR:root:Maximum window size reached.
ERROR:root:Check data and character list!
```

**Comment by lumaku** [comment]
I guess you used a Transformer-based model? Memory consumption explodes on files longer than 350s - 500s.

RNN-based models are usually slower, but require less memory. With an RNN-based model in espnet 2, I can decode and align audio files of up to 10.000s at once with less than 25 GB RAM memory consumption. If you have a RTX 3090 TI you can even do it on GPU. 

On audio files longer than 10k s, Pytorch throws a segfault because the tensors get too large. For those larger files, you could make inference on parts of that file and concatenate the result.


For NeMo, I am not familiar with how CTC segmentation is integrated in the toolkit. The `IndexError` says that the text did not fit to the audio. As CTC segmentation does not provide forced alignments, aligning may fail if the label sequence does not fit to the audio. It then widens the search radius. In your case it reached the preconfigured maximum of 64000. You can try to increase the window size to 250000. Another possible cause for the `IndexError` could be that the input text was not properly partitioned into utterances at text preprocessing and the utterance was to long to align. Check your input data!

**Comment by lumaku** [comment]
@SenYan1999
I took a quick look at the Nvidia implementation, and I think that the issue is that they separated the utterances at the sentence end which is marked by a dot `.`. Now, if you have Chinese text, you probably have a different sentence ending, i.e. `。` which is not included in the splitting character list in `prepare_data.py`. You could add this as a split symbol with the parameter `--additional_split_symbols`.
https://github.com/NVIDIA/NeMo/blob/main/tools/ctc_segmentation/scripts/prepare_data.py#L198

**Comment by SenYan1999** [comment]
My input text is english audio, and I thought this is because the window size is too slow when the default max window size is 64000. After I change the max window size to 128000, I can successfully run the code.

Really sorry that I don't reply in time...

Thank you very much for your help!

**Comment by lumaku** [comment]
Usually the window size is chosen so that is can fit the longest sentence (or can jump over unrelated sentence parts).
A window size of longer than 42s (64k frames) is unusual.
Check your output data....

Please note that NeMo uses a different version of the  ctc-segmentation Python package with slightly different text preprocessing.

But well. Happy to help!
