### ISSUE TITLE
The problem of min_avg ?

### ISSUE THREAD

**Issue by ziyu123** [lumaku/ctc-segmentation#32]
when i determine utterance segment, my char_probs is softmax, not log_softmax, so 
the line https://github.com/lumaku/ctc-segmentation/blob/69bd9b53b7b82ad926d35e7b280f957ed299a7db/ctc_segmentation/ctc_segmentation.py#L403C1-L403C1 
in  determine_utterance_segments function has some error.
i think should be: 
```
min_avg = np.finfo(np.float64).max
or 
min_avg = np.float64(999999999.0)
```
and line 404
````
for t in range(start_t, end_t - n +1):
````

**Comment by lumaku** [comment]
Due to numerical stability, the calculations should be done in log space. This is a best practice, and widely done in sequence classification. With only regular Softmax output values, some floating point values in the Trellis will underflow. Therefore, all calculations are optimized for log space.

As the case starting in line 404 signifies a worst-case metric, the probability starts at 100%, i.e., `min_avg = np.float64(0.0)` in log space, and then is iteratively reduced. Furthermore, `for t in range(start_t, end_t - n +1)` may cause an off-by-one error, if the audio is empty, or, if the `t` in `char_probs[t : t + n]` references the last time step.
